openapi: 3.0.0
info:
  title: Automated Glasshouse
  description: REST API for automated glasshouse.
  version: 0.1.0

servers:
  - url: http://localhost:3000
    description: LOCALHOST
  - url: https://automated-glasshouse-service.herokuapp.com
    description: PROD

consumes:
  - application/json
produces:
  - application/json

paths:
  /api/ping:
    get:
      summary: Used to test application availability
      description:
      parameters:
        - $ref: '#/components/parameters/CorrelationParam'
      responses:
        '200':    # status code
          description: Application is up and running
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Api not responding

  /api/sensor/complete:
    get:
      summary: Used to get sensor data from MongoDB
      description:
      parameters:
        - $ref: '#/components/parameters/CorrelationParam'
      responses:
        '200':    # status code
          description: Application is up and running
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Api not responding

  /api/sensorNow/last:
    get:
      summary: Used to get last sensor data from MongoDB
      description:
      parameters:
        - $ref: '#/components/parameters/CorrelationParam'
      responses:
        '200':    # status code
          description: Application is up and running
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Api not responding

  /api/sensor/current:
    post:
      summary: Used to get sensor data of cuttent date & time from MongoDB
      description:
      parameters:
        - $ref: '#/components/parameters/CorrelationParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/definitions/current'

      responses:
        '200':    # status code
          description: Application is up and running
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Api not responding

  /api/samples: # Doesnt actually work, its just an example
    post:
      summary: Just a sample route
      parameters:
        - $ref: '#/components/parameters/CorrelationParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/definitions/sample'

      responses:
        '200':
          description: returns a successful response
          content:
            application/json:
              schema:
                type: object
        '400':
          description: return if any validation failed for incoming request payload
          content:
            application/json:
              schema:
                type: object
        '503':
          description: returns a failed response
          content:
            application/json:
              schema:
                type: object

components: # used to put uuid into header
  parameters:
    CorrelationParam:
      in: header
      name: Correlation-Id
      schema:
        type: string
        format: uuid
        default: 520d7767-e766-4222-ba94-4b18fd0ebd2d
      required: true

definitions: # example definitions for sample
    current:
      type: object
      properties:
        date:
          type: string
        time:
          type: string
      
    sample:
      type: object
      properties:
        person:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            emailAddress:
              type: string
        method:
          type: object
          properties:
            route:
              type: string
            type:
              type: string
            action:
              type: string
